### ISSUE TITLE
Whitespace at end of block?

### ISSUE THREAD

**Issue by davywentworth** [thanx/style-guide#10]
the default rule is to remove this whitespace:
```
class
  def something
    ...
  end
  # this whitespace
end
```

previously, adding that whitespace was "required" by our style guide. should we keep it, or stick with the default? I feel like it helps add visual clarity.

**Comment by millenniumiguana** [comment]
that whitespace drives me nuts tbh :)

**Comment by marcferna** [comment]
I would say remove it

**Comment by drn** [comment]
I vote for removing white space too - keeps it consistent w spec blocks and methods

**Comment by drn** [comment]
for reference, this is the cop that enforces this config - https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutemptylinesaroundclassbody

**Comment by davywentworth** [comment]
SGTM, just checking.
